language: python
python:
- "2.7"
- "3.5" # Debian 9
- "3.7" # Debian 10
- "3.8"
install:
- pip install -r requirements-dev.txt
script:
- python -c 'import bambam'
- flake8 *.py
- autopep8 -d *.py | awk 'BEGIN{had_data=0}{print;had_data=1}END{exit had_data}'
